-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clients
(
    client_id bigserial NOT NULL,
    address character varying(200) COLLATE pg_catalog."default",
    client_name character varying(100) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.contracts
(
    contract_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    contract_date date,
    contract_sum double precision,
    CONSTRAINT contracts_pkey PRIMARY KEY (contract_number)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id bigserial NOT NULL,
    address character varying(100) COLLATE pg_catalog."default",
    inn character varying(255) COLLATE pg_catalog."default",
    employee_name character varying(100) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    role_id bigint,
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public.machines
(
    machine_id bigserial NOT NULL,
    description character varying(200) COLLATE pg_catalog."default",
    machine_name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT machines_pkey PRIMARY KEY (machine_id)
);

CREATE TABLE IF NOT EXISTS public.order_statuses
(
    status_id bigserial NOT NULL,
    status_name character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT order_statuses_pkey PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id bigserial NOT NULL,
    contract_number character varying(20) COLLATE pg_catalog."default",
    client_id bigint,
    employee_id bigint,
    service_id bigint,
    order_status_id bigint,
    order_name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.prints
(
    print_id bigserial NOT NULL,
    print_name character varying(50) COLLATE pg_catalog."default",
    machine_id bigint,
    CONSTRAINT prints_pkey PRIMARY KEY (print_id)
);

CREATE TABLE IF NOT EXISTS public.product_groups
(
    group_id bigserial NOT NULL,
    group_name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT product_groups_pkey PRIMARY KEY (group_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id bigserial NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    product_name character varying(100) COLLATE pg_catalog."default",
    purchase_price double precision,
    group_id bigint,
    supplier_id bigint,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id bigserial NOT NULL,
    role_name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.services
(
    service_id bigserial NOT NULL,
    service_name character varying(100) COLLATE pg_catalog."default",
    price double precision,
    product_id bigint,
    supplier_id bigint,
    CONSTRAINT services_pkey PRIMARY KEY (service_id)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    supplier_id bigserial NOT NULL,
    address character varying(200) COLLATE pg_catalog."default",
    supplier_name character varying(100) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT suppliers_pkey PRIMARY KEY (supplier_id)
);

ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT fkah490190ww1q2a4piuv41hk6e FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fkcbbqf26brulgfgvd0mf74rv4y FOREIGN KEY (order_status_id)
    REFERENCES public.order_statuses (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fkfhl8bv0xn3sj33q2f3scf1bq6 FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fkj7bkj6q0u3681uv3bvq21316i FOREIGN KEY (service_id)
    REFERENCES public.services (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fkm2dep9derpoaehshbkkatam3v FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prints
    ADD CONSTRAINT fkh9y4yd7faxogixxh9f9ul3589 FOREIGN KEY (machine_id)
    REFERENCES public.machines (machine_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fk6i174ixi9087gcvvut45em7fd FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fk9an6554j5j7f3x8rifrgh4phr FOREIGN KEY (group_id)
    REFERENCES public.product_groups (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.services
    ADD CONSTRAINT fk16cnuanf4fntklkbbckymn8ky FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.services
    ADD CONSTRAINT fk1oa3splk4m8f9tpipjl04vfgw FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;